"""replace author_username with user_id

Revision ID: 1b43a664914b
Revises: 2b42b5637f4a
Create Date: 2022-05-10 23:20:53.672638

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1b43a664914b'
down_revision = '2b42b5637f4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_items_user_id'), 'items', ['user_id'], unique=False)
    op.drop_column('items', 'author_username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('author_username', mysql.VARCHAR(length=255), nullable=False))
    op.drop_index(op.f('ix_items_user_id'), table_name='items')
    op.drop_column('items', 'user_id')
    # ### end Alembic commands ###
