"""add Categories

Revision ID: 21a75ab1c397
Revises: 007bd05ecf9b
Create Date: 2022-05-14 12:29:44.812691

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from sqlalchemy import Integer, String


# revision identifiers, used by Alembic.
revision = '21a75ab1c397'
down_revision = '007bd05ecf9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_name')
    )

    categories = table('categories',
                       column('id', Integer),
                       column('category_name', String))

    op.bulk_insert(categories, [
        {'category_name': 'Housing'},
        {'category_name': 'Buy/Sale'},
        {'category_name': 'Lost-and-Found'},
        {'category_name': 'Project'},
        {'category_name': 'Services'},
        {'category_name': 'Other'},
    ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    # ### end Alembic commands ###
