"""add bio

Revision ID: 64be81e1a774
Revises: 40d017d81e7c
Create Date: 2022-05-24 18:34:55.220839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64be81e1a774'
down_revision = '40d017d81e7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
