"""add category_id field

Revision ID: 754cbfd8fb0f
Revises: 21a75ab1c397
Create Date: 2022-05-14 13:33:32.144441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '754cbfd8fb0f'
down_revision = '21a75ab1c397'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_items_category_id'), 'items', ['category_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_category_id'), table_name='items')
    op.drop_column('items', 'category_id')
    # ### end Alembic commands ###
