"""add price_type field

Revision ID: b4ef76bca1f6
Revises: 7b3f9da518e8
Create Date: 2022-05-18 17:05:56.084548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4ef76bca1f6'
down_revision = '7b3f9da518e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('price_type', sa.Enum('fixed', 'free', 'negotiable', name='pricetypes'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'price_type')
    # ### end Alembic commands ###
